import 'package:product_list_app/product.dart';

final products = [
  Product(
      name: 'RealMe Pro 5g',
      imageUrl:
          'https://www.91-img.com/gallery_images_uploads/c/5/c58b986356aed7a54cb5fa41dbebe3c145125715.JPG',
      price: 16999,
      description:
      'COF Sealing Process, On-Cell Touch Panel Technology, 10 Touch Points, Oleophobic Coating, Taking Photos Methods: Touch Screen Photography, Volume Button Photography, AI Power: APU3.0, Dual RAM Channel, UFS 3.1 ROM, Dual ROM Channel, 45W Supervooc Charge, Reverse Charging, Wi-Fi Antenna Technology: 2 x 2 MIMO, RF Antenna Technology: 4 x 4 MIMO, Dual Mic Nosie Cancellation, Vibrating Motor Type: Flat Motor, Dual Speaker, Supports L1 WideVine Level, Press to Answer Calls, Wake Up Voice Assistant, Switch the Music, Headphones Monitor, Kids Space, Step Tracker, Game Space, App Market, Theme Store, Clone Phone, Phone Manager, Wallet, Google Lens'
      ),
  Product(
    name: 'Apple 2020 Macbook Air Apple M1',
    imageUrl: 'https://t4.ftcdn.net/jpg/04/08/28/49/240_F_408284912_gatspx1rWCpjCt0UHQ6PWwjJ9wzF2sdZ.jpg',
    price: 71990,
    description: 'This Apple Macbook is powered by the Apple M1 chip and is easily portable so that you can carry it with you anywhere you want. This thin and light notebook is equipped with an 8-core CPU to handle all your tasks more efficiently. The 8-core GPU of this notebook takes graphic-intensive games and apps to a whole new level. It also comes with a 16-core Neural Engine to do machine learning tasks more effectively. Its fan-less design offers silent operations and has a long-lasting battery life which can last up to 18 hours on a single charge',
  ),
  Product(name: 'HP M070 Wired Mechanical Mouse', imageUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/mouse/b/c/o/-original-imahfmchzwptnfsq.jpeg?q=70', price: 299, description: 'HP M070 Ergonomic Wired Mouse/ 1.5M USB Cable/Optical Engine/Accurate Positioning/ 1600 DPI with Adjustable DPI 1000-1200/3 Years Warranty'),
  Product(name: 'Crucial BX500 240 GB Laptop, Desktop Internal Solid State Drive (SSD)', imageUrl: 'https://rukminim2.flixcart.com/image/612/612/ke5zzbk0/internal-hard-drive/b/a/u/crucial-ct480bx500ssd1-original-imafuw9zkzvp64bf.jpeg?q=70', price: 1320, description: 'Crucial BX500 240GB 3D NAND SATA 2.5-inch SSD , Compatibility tool: https://www.crucial.in/store/systemscanner'),
  Product(name: 'Oakter mini ups 12v wi-fi Power Backup for Router', imageUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/mini-ups/v/c/a/-original-imagycu2wbmshpcm.jpeg?q=70', price: 1399, description: 'FRUSTRATED BY POWER CUTS - Is it not ironic that every device we use for the Internet such as Mobile, Tablets, Smart Watches, Laptops etc comes with a battery but there is no battery backup for WiFi Router itself? MiniUPS is built to do just that. UNINTERRUPTED POWER TO ROUTER - Oakter Mini UPS can ensure uninterrupted power backup to your 12v DC WiFi Router during frequent power cuts and switch over to generators. POWER BACKUP FOR YOUR WIFI ROUTER - Upto 4 Hours of uninterrupted power backup, depending on current consumption of router. BRIDGE CONNECTOR - Mini UPS for WiFi Router comes with additional bridge connectors that support all Major 12V DC WiFi Routers, Broadband Routers, Set-top box and CCTV. SMART INTELLIGENT CHARGING - Oakter Mini UPS for WiFi Router having an intelligent battery management system, charges itself when there is electricity. Mini UPS is an online UPS for WiFi router thus does not require switching between two paths in case of power failure. PLUG-N-PLAY, DIY FRIENDLY - Oakter Mini UPS is DIY-friendly and is easy to install. In fact, you can connect this DIY-friendly device to the WiFi or WiFi/ADSL router yourself in no time. Mini UPS does not support Jio AirFiber.'),
  Product(name: 'Portronics POR-421 My Buddy K Laptop Stand', imageUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/laptop-stand/q/j/e/260-por-421-my-buddy-k-portronics-original-imaggnshyzsvv7wt.jpeg?q=70', price: 194, description: 'My Buddy K is user Friendly Design Collapsible Lightweight, Portable, Solid & Stable Construction. Relieves the wrist, neck and spine fatigue caused by using a laptop for long periods of time. Easy to Use Just use your thumbs and fore?ngers to pinch outward to open or press close quickly. Minimalism Your laptop will have better ventilation and extended life. Raises notebook screen height to eye level for better ergonomics, you can take it to anywhere you wanna to go. A compact and lighter design is also fully collapsible, making this ideal for business travelers and as a gift.'),
];
